"""Fixtures for the export-content tests: small S-matrices and one provenance.

The S-parameter values are chosen to encode their own position -- S(r,c) is
``complex(r, c)`` in the multiport fixtures -- so an ordering mistake is visible
by reading the expected string rather than by trusting a comment about it. A
transposed 2-port and a row-major 3-port cannot look alike under that scheme.

NOTHING HERE IS READ FROM DISK, and the expected strings in ``test_export.py``
are inline rather than golden files. Line endings are the whole reason: a
checked-out fixture file's endings depend on git's autocrlf setting and on which
OS the CI leg runs, so a "\\n"-exact assertion against a file on disk would pass
on Linux and fail on Windows for reasons that have nothing to do with the code.
"""

from __future__ import annotations

from datetime import datetime, timezone

from hfss_agent.contract import (
    CONTRACT_VERSION,
    ComplexSample,
    ProvenanceRecord,
    SolvedData,
    Variation,
)

GHZ = 1.0e9


def sample(value: complex) -> ComplexSample:
    return ComplexSample(real=value.real, imag=value.imag)


def solved(
    frequencies: list[float], s_parameters: dict[str, list[complex]]
) -> SolvedData:
    return SolvedData(
        frequencies=list(frequencies),
        s_parameters={
            key: [sample(value) for value in values]
            for key, values in s_parameters.items()
        },
    )


def positional_matrix(port_count: int, frequencies: list[float]) -> SolvedData:
    """An N x N matrix whose every entry states its own position.

    ``S(r,c)`` is ``complex(r, c)`` at every frequency, so the exported text
    reads as a sequence of coordinates and any reordering is legible on sight.
    """
    return solved(
        frequencies,
        {
            f"S({row},{column})": [complex(row, column) for _ in frequencies]
            for row in range(1, port_count + 1)
            for column in range(1, port_count + 1)
        },
    )


def provenance_for(
    project: str = "patch_antenna",
    design: str = "HFSSDesign1",
    reference_impedance: float = 50.0,
) -> ProvenanceRecord:
    """A complete ProvenanceRecord; the two untrusted fields are parameterised.

    ``project`` and ``design`` are the ``UntrustedStr`` fields, so they are the
    ones the hostile-content test needs to vary.
    """
    return ProvenanceRecord(
        project=project,
        design=design,
        solution_type="DrivenModal",
        setup="Setup1",
        sweep="Sweep1",
        variation=Variation(
            values={"width": "2.0mm", "freq": "2.4GHz"},
            variation_hash="sha256:deadbeefcafef00d",
        ),
        expression="dB(S(1,1))",
        reference_impedance=reference_impedance,
        solve_timestamp=datetime(2026, 7, 17, 9, 30, tzinfo=timezone.utc),
        freshness_status="fresh",
        snapshot_id="snap-001",
        contract_version=CONTRACT_VERSION,
        wrapper_version="0.2.0",
    )


# The header block every expected string below starts with. Written out once,
# verbatim, so each test's expected string states only what is specific to it --
# and so a header change has exactly one place to update and one test
# (``test_header_block_is_exact``) that pins it literally.
EXPECTED_HEADER_TEMPLATE = (
    "! Touchstone 1.0 ({port_count}-port) generated by hfss-agent\n"
    "! project: patch_antenna\n"
    "! design: HFSSDesign1\n"
    "! setup: Setup1\n"
    "! sweep: Sweep1\n"
    "! variation: freq=2.4GHz; width=2.0mm\n"
    "! variation_hash: sha256:deadbeefcafef00d\n"
    "! solve_timestamp: 2026-07-17T09:30:00+00:00\n"
    "! reference_impedance_ohm: 50.0\n"
    "! wrapper_version: 0.2.0\n"
    "! contract_version: snapshot-3.0.0\n"
    "# HZ S RI R 50.0\n"
)


def expected_header(port_count: int) -> str:
    return EXPECTED_HEADER_TEMPLATE.format(port_count=port_count)


# The trailing provenance columns every CSV row carries, as they appear once
# quoted. Only ``variation`` needs quoting (it contains a comma-free "; " but the
# variation text itself has no comma -- the quoting that does appear is on the
# S-parameter headers).
CSV_PROVENANCE_HEADERS = (
    "project,design,setup,sweep,variation,variation_hash,"
    "solve_timestamp,reference_impedance_ohm,wrapper_version,contract_version"
)
CSV_PROVENANCE_VALUES = (
    "patch_antenna,HFSSDesign1,Setup1,Sweep1,freq=2.4GHz; width=2.0mm,"
    "sha256:deadbeefcafef00d,2026-07-17T09:30:00+00:00,50.0,0.2.0,snapshot-3.0.0"
)
