"""Export content — byte-exact Touchstone and CSV, and the refusals.

Every expectation here is an inline string with explicit "\\n", compared with
``==`` rather than by parsing the output back. An exporter is one of the few
places where "it round-trips" is not good enough: the file goes to another tool,
so the bytes ARE the contract, and a test that re-parses its own output would
agree with any self-consistent mistake.

The ordering tests are the point of this file. Touchstone v1.0's 2-port
transposition is the trap -- see ``_matrix_rows`` -- so it gets an assertion that
names the wrong answer as well as the right one.
"""

from __future__ import annotations

import pytest
from export_helpers import (
    CSV_PROVENANCE_HEADERS,
    CSV_PROVENANCE_VALUES,
    GHZ,
    expected_header,
    positional_matrix,
    provenance_for,
    solved,
)

from hfss_agent.metrics import (
    ExportContentError,
    csv_content,
    touchstone_content,
    touchstone_port_count,
)

# --- Touchstone: the header and option line -----------------------------------


def test_header_block_is_exact() -> None:
    content = touchstone_content(
        positional_matrix(1, [1 * GHZ]), provenance_for()
    )
    assert content.startswith(
        "! Touchstone 1.0 (1-port) generated by hfss-agent\n"
        "! project: patch_antenna\n"
        "! design: HFSSDesign1\n"
        "! setup: Setup1\n"
        "! sweep: Sweep1\n"
        "! variation: freq=2.4GHz; width=2.0mm\n"
        "! variation_hash: sha256:deadbeefcafef00d\n"
        "! solve_timestamp: 2026-07-17T09:30:00+00:00\n"
        "! reference_impedance_ohm: 50.0\n"
        "! wrapper_version: 0.2.0\n"
        "! contract_version: snapshot-4.0.0\n"
        "# HZ S RI R 50.0\n"
    )


def test_reference_impedance_comes_from_the_provenance_and_is_never_defaulted() -> None:
    content = touchstone_content(
        positional_matrix(1, [1 * GHZ]), provenance_for(reference_impedance=75.0)
    )
    assert "# HZ S RI R 75.0\n" in content
    assert "! reference_impedance_ohm: 75.0\n" in content
    # The option line and the comment state one number from one source, so they
    # cannot drift apart.
    assert "50.0" not in content


# --- Touchstone: value ordering, the part that must be exact ------------------


def test_one_port_is_one_line_per_frequency() -> None:
    data = solved(
        [1 * GHZ, 2 * GHZ], {"S(1,1)": [0.5 + 0.25j, -0.5 - 0.25j]}
    )
    assert touchstone_content(data, provenance_for()) == expected_header(1) + (
        "1000000000.0 0.5 0.25\n"
        "2000000000.0 -0.5 -0.25\n"
    )


def test_two_port_is_transposed_s11_s21_s12_s22() -> None:
    # Deliberately asymmetric: S(1,2) != S(2,1), so the transposition is visible.
    data = solved(
        [1 * GHZ],
        {
            "S(1,1)": [0.1 + 0.2j],
            "S(1,2)": [0.3 + 0.4j],
            "S(2,1)": [0.5 + 0.6j],
            "S(2,2)": [0.7 + 0.8j],
        },
    )
    content = touchstone_content(data, provenance_for())
    assert content == expected_header(2) + (
        "1000000000.0 0.1 0.2 0.5 0.6 0.3 0.4 0.7 0.8\n"
    )
    # Naming the wrong answer explicitly: row-major would put S(1,2) second.
    # A future "fix" to row-major swaps S21 and S12 in every .s2p we write.
    assert "1000000000.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8\n" not in content


def test_three_port_is_row_major_one_matrix_row_per_line() -> None:
    # S(r,c) == complex(r, c), so each pair reads as its own coordinates.
    content = touchstone_content(positional_matrix(3, [1 * GHZ]), provenance_for())
    assert content == expected_header(3) + (
        "1000000000.0 1.0 1.0 1.0 2.0 1.0 3.0\n"
        "        2.0 1.0 2.0 2.0 2.0 3.0\n"
        "        3.0 1.0 3.0 2.0 3.0 3.0\n"
    )


def test_three_port_needs_no_continuation_lines() -> None:
    # Stated outright because it is why the wrapping test below is 5-port: a
    # 3-port row is 3 pairs, under the 4-pair limit, so no 3-port file can
    # exercise wrapping at all.
    content = touchstone_content(positional_matrix(3, [1 * GHZ]), provenance_for())
    data_lines = [
        line for line in content.splitlines() if not line.startswith(("!", "#"))
    ]
    assert len(data_lines) == 3  # one per matrix row, none of them a continuation


def test_five_port_wraps_at_four_pairs_per_line() -> None:
    # Row 1 is 5 pairs: 4 on the frequency line, 1 on a continuation line. Then
    # row 2 starts a new line rather than filling up the continuation.
    content = touchstone_content(positional_matrix(5, [1 * GHZ]), provenance_for())
    assert content == expected_header(5) + (
        "1000000000.0 1.0 1.0 1.0 2.0 1.0 3.0 1.0 4.0\n"
        "        1.0 5.0\n"
        "        2.0 1.0 2.0 2.0 2.0 3.0 2.0 4.0\n"
        "        2.0 5.0\n"
        "        3.0 1.0 3.0 2.0 3.0 3.0 3.0 4.0\n"
        "        3.0 5.0\n"
        "        4.0 1.0 4.0 2.0 4.0 3.0 4.0 4.0\n"
        "        4.0 5.0\n"
        "        5.0 1.0 5.0 2.0 5.0 3.0 5.0 4.0\n"
        "        5.0 5.0\n"
    )


def test_two_port_keeps_all_four_pairs_on_one_line() -> None:
    # The 4-pair limit and the 2-port line coincide exactly; asserting it so a
    # change to _MAX_PAIRS_PER_LINE cannot quietly split a .s2p line in two.
    content = touchstone_content(positional_matrix(2, [1 * GHZ]), provenance_for())
    data_lines = [
        line for line in content.splitlines() if not line.startswith(("!", "#"))
    ]
    assert data_lines == ["1000000000.0 1.0 1.0 2.0 1.0 1.0 2.0 2.0 2.0"]


# --- Touchstone: precision and line endings -----------------------------------


def test_values_keep_full_round_trippable_precision() -> None:
    awkward = 0.1234567890123456789
    data = solved([1 * GHZ], {"S(1,1)": [complex(awkward, -awkward)]})
    content = touchstone_content(data, provenance_for())
    # repr() round-trips exactly; a %.6f-style format would have lost digits.
    assert f"1000000000.0 {awkward!r} {-awkward!r}\n" in content
    assert float(repr(awkward)) == awkward


def test_no_carriage_returns_anywhere() -> None:
    for content in (
        touchstone_content(positional_matrix(3, [1 * GHZ, 2 * GHZ]), provenance_for()),
        csv_content(positional_matrix(3, [1 * GHZ, 2 * GHZ]), provenance_for()),
    ):
        assert "\r" not in content
        assert content.endswith("\n")


# --- Touchstone: refusals -----------------------------------------------------


def test_an_incomplete_matrix_is_refused_and_names_what_is_missing() -> None:
    data = solved(
        [1 * GHZ],
        {
            "S(1,1)": [0.1 + 0.0j],
            "S(1,2)": [0.2 + 0.0j],
            "S(2,1)": [0.3 + 0.0j],
        },
    )
    with pytest.raises(ExportContentError) as caught:
        touchstone_content(data, provenance_for())
    message = str(caught.value)
    assert "incomplete for 2 ports" in message
    assert "S(2,2)" in message
    # The refusal must not offer a padded alternative, and none is produced.
    assert "missing S(2,2)" in message


def test_a_larger_gap_names_every_missing_entry() -> None:
    data = solved([1 * GHZ], {"S(1,1)": [0j], "S(3,3)": [0j]})
    with pytest.raises(ExportContentError) as caught:
        touchstone_content(data, provenance_for())
    message = str(caught.value)
    assert "incomplete for 3 ports" in message
    for missing in (
        "S(1,2)", "S(1,3)", "S(2,1)", "S(2,2)", "S(2,3)", "S(3,1)", "S(3,2)"
    ):
        assert missing in message


def test_a_key_that_is_not_an_s_parameter_is_refused() -> None:
    # "dB(S(1,1))" is a real HFSS expression shape and is not an S-parameter
    # matrix entry; inferring a port count from it would be a guess.
    data = solved([1 * GHZ], {"dB(S(1,1))": [0.1 + 0.0j]})
    with pytest.raises(ExportContentError, match="not in canonical"):
        touchstone_content(data, provenance_for())


@pytest.mark.parametrize(
    "key", ["s(1,1)", "s( 1 , 1 )", "S(1, 1)", " S(1,1)", "S(1,1) ", "S (1,1)"]
)
def test_a_non_canonical_spelling_is_refused(key: str) -> None:
    """Spellings a tolerant parser would have accepted are now refused.

    Each of these resolves unambiguously to position (1, 1), so absorbing them
    would produce a correct file. That is exactly why they are refused: a key
    spelled any of these ways means PyAEDT emitted something other than what
    ``SolvedData``'s docstring assumes, and quietly succeeding would throw that
    discovery away. See ``_S_PARAM_KEY``.
    """
    data = solved([1 * GHZ], {key: [0.1 + 0.0j]})
    with pytest.raises(ExportContentError) as caught:
        touchstone_content(data, provenance_for())
    message = str(caught.value)
    assert "not in canonical" in message
    assert repr(key) in message, "the refusal must name the offending key"
    # The message points at an upstream bug rather than at this parser.
    assert "upstream bug" in message


def test_a_duplicated_matrix_position_is_refused() -> None:
    # BOTH keys are canonical by the strict regex -- "\\d+" accepts a leading
    # zero -- yet both resolve to (1, 1). This is why the duplicate check is
    # still reachable after the parser was tightened, and why tightening it did
    # not make this test redundant.
    data = solved([1 * GHZ], {"S(1,1)": [0.1 + 0.0j], "S(01,1)": [0.9 + 0.0j]})
    with pytest.raises(ExportContentError, match="supplied twice") as caught:
        touchstone_content(data, provenance_for())
    message = str(caught.value)
    assert "'S(1,1)'" in message and "'S(01,1)'" in message


def test_a_misaligned_series_is_refused() -> None:
    data = solved([1 * GHZ, 2 * GHZ], {"S(1,1)": [0.1 + 0.0j]})
    with pytest.raises(ExportContentError, match="align index-for-index"):
        touchstone_content(data, provenance_for())


@pytest.mark.parametrize(
    ("frequencies", "expected"),
    [
        ([], "no frequencies"),
        ([2 * GHZ, 1 * GHZ], "strictly increasing"),
        ([1 * GHZ, 1 * GHZ], "strictly increasing"),
    ],
)
def test_unusable_frequency_arrays_are_refused(
    frequencies: list[float], expected: str
) -> None:
    data = solved(frequencies, {"S(1,1)": [0.1 + 0.0j] * len(frequencies)})
    with pytest.raises(ExportContentError, match=expected):
        touchstone_content(data, provenance_for())


def test_an_empty_s_parameter_map_is_refused() -> None:
    data = solved([1 * GHZ], {})
    with pytest.raises(ExportContentError, match="no S-parameters"):
        touchstone_content(data, provenance_for())


# --- untrusted strings cannot forge a data line -------------------------------


def test_a_newline_in_an_untrusted_name_cannot_inject_a_data_line() -> None:
    # The attack this guards: a project name that closes the "!" comment and
    # opens what a Touchstone reader would take for a measured point.
    hostile = "patch\n5000000000.0 0.0 0.0"
    content = touchstone_content(
        positional_matrix(1, [1 * GHZ]), provenance_for(project=hostile)
    )
    comment_lines = [line for line in content.splitlines() if line.startswith("!")]
    data_lines = [
        line for line in content.splitlines() if not line.startswith(("!", "#"))
    ]
    assert data_lines == ["1000000000.0 1.0 1.0"], "a forged point reached the data"
    assert any("patch 5000000000.0 0.0 0.0" in line for line in comment_lines)
    assert "\n5000000000.0" not in content


def test_a_newline_in_an_untrusted_name_cannot_forge_a_csv_row() -> None:
    hostile = "patch\n9e9,0,0"
    content = csv_content(
        positional_matrix(1, [1 * GHZ]), provenance_for(design=hostile)
    )
    assert len(content.splitlines()) == 2  # header + one data row, nothing forged
    assert '"patch 9e9,0,0"' in content  # neutralised, then correctly quoted


# --- CSV ----------------------------------------------------------------------


def test_csv_content_is_exact_for_one_port() -> None:
    data = solved([1 * GHZ, 2 * GHZ], {"S(1,1)": [0.5 + 0.25j, -0.5 - 0.25j]})
    assert csv_content(data, provenance_for()) == (
        'frequency_hz,"S(1,1)_real","S(1,1)_imag",' + CSV_PROVENANCE_HEADERS + "\n"
        "1000000000.0,0.5,0.25," + CSV_PROVENANCE_VALUES + "\n"
        "2000000000.0,-0.5,-0.25," + CSV_PROVENANCE_VALUES + "\n"
    )


def test_csv_s_parameter_columns_are_row_major_even_for_two_port() -> None:
    # Deliberately NOT the Touchstone transposition: CSV columns are labelled,
    # so there is no legacy ordering a reader has to know about.
    data = solved(
        [1 * GHZ],
        {
            "S(1,1)": [0.1 + 0.2j],
            "S(1,2)": [0.3 + 0.4j],
            "S(2,1)": [0.5 + 0.6j],
            "S(2,2)": [0.7 + 0.8j],
        },
    )
    content = csv_content(data, provenance_for())
    header, row = content.splitlines()
    assert header.startswith(
        'frequency_hz,"S(1,1)_real","S(1,1)_imag","S(1,2)_real","S(1,2)_imag",'
        '"S(2,1)_real","S(2,1)_imag","S(2,2)_real","S(2,2)_imag",'
    )
    assert row.startswith("1000000000.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,")


def test_csv_parses_back_with_the_stdlib_reader() -> None:
    # The one place re-parsing is the right check: the claim is that this output
    # is ordinary RFC-4180 that a standard reader handles with no special casing.
    # csv is imported HERE, in the test, never in export.py.
    import csv
    import io

    data = positional_matrix(2, [1 * GHZ, 2 * GHZ])
    rows = list(csv.DictReader(io.StringIO(csv_content(data, provenance_for()))))
    assert len(rows) == 2
    assert rows[0]["frequency_hz"] == "1000000000.0"
    assert rows[0]["S(2,1)_real"] == "2.0"
    assert rows[0]["S(2,1)_imag"] == "1.0"
    # Provenance is on every row, which is the point of carrying it as columns.
    for row in rows:
        assert row["project"] == "patch_antenna"
        assert row["variation"] == "freq=2.4GHz; width=2.0mm"
        assert row["reference_impedance_ohm"] == "50.0"


def test_csv_quotes_a_field_containing_a_comma() -> None:
    content = csv_content(
        positional_matrix(1, [1 * GHZ]), provenance_for(project="a,b")
    )
    assert '"a,b"' in content


def test_csv_doubles_an_internal_quote() -> None:
    content = csv_content(
        positional_matrix(1, [1 * GHZ]), provenance_for(project='say "hi"')
    )
    assert '"say ""hi"""' in content


def test_csv_refuses_the_same_incomplete_matrix_touchstone_does() -> None:
    data = solved([1 * GHZ], {"S(1,1)": [0j], "S(2,2)": [0j]})
    with pytest.raises(ExportContentError, match="incomplete for 2 ports"):
        csv_content(data, provenance_for())


# --- the .sNp suffix seam -----------------------------------------------------


@pytest.mark.parametrize("port_count", [1, 2, 3, 4, 10])
def test_touchstone_port_count_matches_the_exported_content(port_count: int) -> None:
    """The count a ``.sNp`` filename must encode, derived from the same inference.

    Asserted AGAINST THE CONTENT rather than against the fixture's parameter: the
    point of the function is that the filename and the bytes cannot disagree, so
    the test checks that the number it reports is the number the header states.
    A second inference path would pass a fixture-parameter check and still drift.

    N = 10 is included because it is where a flattened filename convention breaks
    down, and N = 2 because that is the port count whose column-major ordering
    makes a wrong suffix actively dangerous rather than merely wrong.
    """
    data = positional_matrix(port_count, [1 * GHZ])
    assert touchstone_port_count(data) == port_count
    assert touchstone_content(data, provenance_for()).startswith(
        f"! Touchstone 1.0 ({touchstone_port_count(data)}-port)"
    )


def test_touchstone_port_count_refuses_what_the_content_refuses() -> None:
    # The count cannot be honestly reported for a matrix that could not be
    # honestly exported, so it raises for the same reasons and via the same code.
    data = solved([1 * GHZ], {"S(1,1)": [0j], "S(2,2)": [0j]})
    with pytest.raises(ExportContentError, match="incomplete for 2 ports"):
        touchstone_port_count(data)


# --- the no-file-I/O claim ----------------------------------------------------


def test_no_file_io_is_reachable_from_export() -> None:
    """Where the no-I/O guarantee is actually enforced, stated for the record.

    The real enforcement is static and lives in the boundary suite:
    ``tests/boundary/test_metrics_import_audit.py::test_pure_files_import_nothing_io_capable``
    parses ``export.py`` and fails on any import of os/io/pathlib/shutil/
    tempfile/subprocess/socket/urllib/http/requests, or any call to ``open``.
    That is the test to look at; this one only records that the functions return
    strings and touch nothing, so the two claims are not confused for each other.
    """
    content = touchstone_content(positional_matrix(2, [1 * GHZ]), provenance_for())
    assert isinstance(content, str)
    csv_out = csv_content(positional_matrix(2, [1 * GHZ]), provenance_for())
    assert isinstance(csv_out, str)
